name: Deploy Backend

on:
  push:
    paths:
      - 'FullStackProjects/src/main/java/com/project/EMS/emp-app/src/**'            # Adjust path if needed
      - '.github/workflows/deploy-backend.yml'
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1   # Change to your region

      - name: Download latest backend JAR from S3
        run: |
          aws s3 cp s3://myjarbucketsandhya/EMS-0.0.1-SNAPSHOT.jar ./backend-latest.jar

      - name: Run backend JAR
        run: |
          java -jar backend-latest.jar
